# Generated by Django 3.1.7 on 2021-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('sources', models.ManyToManyField(to='isro.source')),
            ],
        ),
    ]
