# Generated by Django 3.1.7 on 2021-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isro', '0003_auto_20210315_1001'),
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubs',
            name='sources',
            field=models.ManyToManyField(related_name='_pubs_sources_+', to='isro.source'),
        ),
    ]
