# Generated by Django 3.1.7 on 2021-03-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0002_auto_20210315_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubs',
            name='link',
            field=models.URLField(default='', max_length=300),
        ),
    ]
