# Generated by Django 3.1.7 on 2021-03-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isro', '0001_initial'),
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='publications',
            field=models.ManyToManyField(blank=True, to='pub.pubs'),
        ),
    ]
