# Generated by Django 3.1.7 on 2021-03-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isro', '0002_source_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='publications',
            new_name='pubs',
        ),
    ]
