# Generated by Django 3.1.7 on 2021-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isro', '0003_auto_20210315_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='astrosat',
            field=models.BooleanField(default=False),
        ),
    ]
